### ISSUE TITLE
IA can't start after laptop crash

### ISSUE THREAD

**Issue by aisharp** [marius00/iagd#85]
IA no longer start after my laptop crash, uninstalling and reinstalling the latest version still not solve the problem. When I click IA to start, it shows for a brief second on Task Manager, then it's vanish. Each time it vanish, it create this 3 logs on Event Viewer. Strangely enough using the older version works perfectly.

[Windows Error Reporting Event ID 1001.txt](https://github.com/marius00/iagd/files/3788144/Windows.Error.Reporting.Event.ID.1001.txt)

[Application Error Event ID 1000.txt](https://github.com/marius00/iagd/files/3788145/Application.Error.Event.ID.1000.txt)

[NET Runtime Event ID 1026.txt](https://github.com/marius00/iagd/files/3788148/NET.Runtime.Event.ID.1026.txt)

**Comment by marius00** [comment]
This was fixed in 8ac1634ae2b117f47f7cbccc8f4153d89e582a45 I believe

**Comment by marius00** [comment]
Can you verify if the problem is solved?

**Comment by aisharp** [comment]
Can confirm that the problem is still there. I uninstall any IA I have both the old version and new version, then re-download the installer from (http://grimdawn.dreamcrash.org/ia/) and install it in other location but it still not start.

But today I accidentally find a way to solve the problem. I go to the C:\Users\USER\AppData\Local\EvilSoft, I copy the backup file and then permanently delete the folder EvilSoft there, then restart the app and it start, it is working and no longer just vanish from task manager. After that I import the latest backup and everything works fine now. I may try this again if my computer crash or if there is a power failure again in my place.

Out of curiosity I check the newly created log file, It show that I'm using the version 1.2.7144.26092 even though Mr. Pete from GD forum state that the new version is 1.2.7240.25671 (https://forums.crateentertainment.com/t/tool-grim-dawn-item-assistant/30491/2511)
Here I upload my latest log file where it show that I'm using 1.2.7144.26092 instead of 1.2.7240.25671, there is also no prompt to update from my current IA, so how it is to update to that version?

[log.txt](https://github.com/marius00/iagd/files/3850972/log.txt)

**Comment by marius00** [comment]
Get the installer from http://grimdawn.dreamcrash.org/ia/latest.php 

The one on the website is not the latest.

**Comment by aisharp** [comment]
Aah I didn't know that there are beta version available and the one on the website is not the latest one. Thanks for that.
